---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[phing::default]
    attributes:
